name: Cypress Tests
run-name: Run Cypress - ${{ github.event.inputs.testType || 'smoke' }} tests in ${{ github.event.inputs.environment || 'development' }} by @${{ github.actor }}
on: 
  workflow_dispatch:
    inputs:
      testType:
        type: choice
        description: Select Test Type
        required: true
        default: 'smoke'
        options: ['smoke','regression']
      environment:
        type: choice
        description: Select Environment
        required: true
        default: 'development'
        options: ['development','testing-1','testing-2','staging']
  pull_request:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.PROJECT_ID }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          COMMIT_INFO_MESSAGE: Run Cypress - ${{ github.event.inputs.testType || 'smoke' }} tests in ${{ github.event.inputs.environment || 'development' }} by @${{ github.actor }}
          DESCOPE_PROJECT_ID: ${{ secrets.DESCOPE_PROJECT_ID }}
          DESCOPE_MANAGEMENT_KEY: ${{ secrets.DESCOPE_MANAGEMENT_KEY }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        with:
          record: true
          parallel: true
          build: npx cypress info
          command: npm run cypress:${{ github.event.inputs.testType || 'smoke' }}-${{ github.event.inputs.environment || 'development' }}
